version: "3"
services:
  api:
    build:
      context: .
    image: api.reidchatham.com-users:dev
    environment:
      JWT_PUBLIC
      JWT_SECRET
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      EMAIL_CONFIRMATION: 'off'
      OPEN_REGISTRATION: 'on'
      EXPOSED_PORT: 443
    # env_file:
    #   - ./env/postgres.env
    ports:
      - 443:443
    # volumes:
    #   - ./:/app
    depends_on:
      - "db"
      
  db:
    image: postgres:latest
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    # ports:
    #   - 5432:5432
    # env_file:
    #   - ./env/postgres.env
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

volumes:
    db_data: {}
