version: "3"
services:
  api:
    build:
      context: .
    image: api.reidchatham.com-users:dev
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      JWT_PUBLIC: ${JWT_PUBLIC}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_CONFIRMATION: 'off'
      OPEN_REGISTRATION: 'on'
      # SENDGRID_API_KEY:
      EXPOSED_PORT: 443
    ports:
      - 443:443
    depends_on:
      - "db"

  db:
    image: postgres:latest
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

volumes:
    db_data: {}
