version: "3"
services:
  api:
    build:
      context: .
    image: api.reidchatham.com-users:dev
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: test
      DATABASE_DB: service_users
      SLEEP_LENGTH: 5
      JWT_PUBLIC: n-value-from-jwt
      JWT_SECRET: d-value-from-jwt
      # SENDGRID_API_KEY: add-your-key
      # EMAIL_FROM: example@email.com
      # EMAIL_URL: http://localhost:8080/v1/users/activate
      # EMAIL_CONFIRMATION: on
      # OPEN_REGISTRATION: on
      EXPOSED_PORT: 443
    ports:
      - 443:443
    # volumes:
    #   - ./:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    volumes:
     - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: service_users
      MYSQL_USER: root
      MYSQL_PASSWORD: test
volumes:
    db_data: {}
